### ISSUE TITLE
How to create my own dataset like Indian_Number_plates.json? 

### ISSUE THREAD

**Issue by pendex900x** [Kshitijpawar/License_Plate_Detection#4]
Do you use some software to do the json file?

I pretend to train number plates but for other country.

**Comment by Kshitijpawar** [comment]
Since bounding boxes generation require manual input I just got this file from Kaggle and parsed through it to obtain images and generate respective .xml files with bounding boxes, however if you do intend to create your own dataset for annotation (.xml with bounding box for each image), you can use LabelImg https://github.com/tzutalin/labelImg

**Comment by pendex900x** [comment]
Thanks!
